// Generated by CoffeeScript 1.6.3
(function() {
  var Cube, Extend, key, value;

  Cube = this.Cube || require('./cube');

  Extend = {
    asyncOK: !!window.Worker,
    _asyncSetup: function(workerURI) {
      var _this = this;
      if (this._worker) {
        return;
      }
      this._worker = new window.Worker(workerURI);
      this._worker.addEventListener('message', function() {
        return _this._asyncEvent.apply(_this, arguments);
      });
      return this._asyncCallbacks = {};
    },
    _asyncEvent: function(e) {
      var callback, callbacks;
      callbacks = this._asyncCallbacks[e.data.cmd];
      if (!(callbacks && callbacks.length)) {
        return;
      }
      callback = callbacks[0];
      callbacks.splice(0, 1);
      return callback(e.data);
    },
    _asyncCallback: function(cmd, callback) {
      var _base;
      (_base = this._asyncCallbacks)[cmd] || (_base[cmd] = []);
      return this._asyncCallbacks[cmd].push(callback);
    },
    asyncInit: function(workerURI, callback) {
      this._asyncSetup(workerURI);
      this._asyncCallback('init', function() {
        return callback();
      });
      return this._worker.postMessage({
        cmd: 'init'
      });
    },
    asyncSolve: function(cube, callback) {
      this._asyncSetup();
      this._asyncCallback('solve', function(data) {
        return callback(data.algorithm);
      });
      return this._worker.postMessage({
        cmd: 'solve',
        cube: cube.toJSON()
      });
    },
    asyncScramble: function(callback) {
      this._asyncSetup();
      this._asyncCallback('solve', function(data) {
        return callback(Cube.inverse(data.algorithm));
      });
      return this._worker.postMessage({
        cmd: 'solve',
        cube: Cube.random().toJSON()
      });
    }
  };

  for (key in Extend) {
    value = Extend[key];
    Cube[key] = value;
  }

}).call(this);
